#!/bin/bash
## Job name:
#SBATCH --job-name=vasp		## relax can be changed to any name 
## Project:
#SBATCH --account=materialsim
## Wall clock limit:
##SBATCH --time=hh:mm:ss
## Memory requirment for the nodes (MB):
##SBATCH --mem-per-cpu=2560
## Number of nodes:
#SBATCH --nodes=1		## number of nodes will be used, from 1 - 8
## Specify all cores on each node:
#SBATCH --ntasks=16		## 8  
##SBATCH --ntasks-per-node=16
##SBATch --cores-per-socket=8	## 

## Do some work:
ulimit -s unlimited

DATE1 = $(date)

cat  > INCAR <<!
  Global Parameters
  ISTART =  0            (Read existing wavefunction; if there)
  # ISPIN =  2           (Spin polarised DFT)
  # ICHARG =  11         (Non-self-consistent: GGA/LDA band structures)
  LREAL  = Auto          (Projection operators: automatic)
  ENCUT  =  400          (Cut-off energy for plane wave basis set, in eV)
  PREC   =  Normal       (Precision level)
  LWAVE  =  F        (Write WAVECAR or not)
  LCHARG =  F        (Write CHGCAR or not)
  ADDGRID=  F        (Increase grid; helps GGA convergence)
 
Electronic Relaxation
  ISMEAR =  0            (Gaussian smearing; metals:1)
  SIGMA  =  0.05         (Smearing value in eV; metals:0.2)
  NELM   =  60           (Max electronic SCF steps)
  NELMIN =  6            (Min electronic SCF steps)
  EDIFF  =  1E-04        (SCF energy convergence; in eV)
  # GGA  =  PS           (PBEsol exchange-correlation)
 
Ionic Relaxation
  NSW    =  100          (Max electronic SCF steps)
  IBRION =  2            (Algorithm: 0-MD; 1-Quasi-New; 2-CG)
  ISIF   =  2            (Stress/relaxation: 2-Ions, 3-Shape/Ions/V, 4-Shape/Ions)
  EDIFFG = -1E-01        (Ionic convergence; eV/AA)
  # ISYM =  2            (Symmetry: 0=none; 2=GGA; 3=hybrids)
 
!

srun /opt/soft/vasp/5.3.2/vasp

grep "reached required accuracy" OUTCAR

if [ $? -eq 0 ] ;then 
    mkdir DOS   #terminated successfully!
    cd DOS
    cp ../CONTCAR ./POSCAR
    cp ../KPOINTS  ../POTCAR ./
else 
    exit
fi

cat  > INCAR <<!
  Global Parameters
  ISTART =  0            (Read existing wavefunction; if there)
  # ISPIN =  2           (Spin polarised DFT)
  # ICHARG =  11         (Non-self-consistent: GGA/LDA band structures)
  LREAL  = Auto          (Projection operators: automatic)
  ENCUT  =  400          (Cut-off energy for plane wave basis set, in eV)
  PREC   =  Normal       (Precision level)
  LWAVE  =  F        (Write WAVECAR or not)
  LCHARG =  F        (Write CHGCAR or not)
  ADDGRID=  F        (Increase grid; helps GGA convergence)
 
Electronic Relaxation
  ISMEAR =  0            (Gaussian smearing; metals:1)
  SIGMA  =  0.05         (Smearing value in eV; metals:0.2)
  NELM   =  60           (Max electronic SCF steps)
  NELMIN =  6            (Min electronic SCF steps)
  EDIFF  =  1E-05        (SCF energy convergence; in eV)
  # GGA  =  PS           (PBEsol exchange-correlation)
  LORBIT =  11           (PDOS)
  
Ionic Relaxation
  NSW    =  0          (Max electronic SCF steps)
  IBRION =  -1            (Algorithm: 0-MD; 1-Quasi-New; 2-CG)
  #ISIF   =  2            (Stress/relaxation: 2-Ions, 3-Shape/Ions/V, 4-Shape/Ions)
  #EDIFFG = -1E-01        (Ionic convergence; eV/AA)
  # ISYM =  2            (Symmetry: 0=none; 2=GGA; 3=hybrids)
 
!

srun /opt/soft/vasp/5.3.2/vasp

DATE2 = $(date)

echo $DATE1 >> timing.log
echo $DATE2 >> timing.log
