#!/bin/bash
## Job name:
#SBATCH --job-name=vasp		## relax can be changed to any name 
## Project:
#SBATCH --account=materialsim
## Wall clock limit:
##SBATCH --time=hh:mm:ss
## Memory requirment for the nodes (MB):
##SBATCH --mem-per-cpu=2560
## Number of nodes:
#SBATCH --nodes=1		## number of nodes will be used, from 1 - 8
## Specify all cores on each node:
#SBATCH --ntasks=16		## 8  
##SBATCH --ntasks-per-node=16
##SBATch --cores-per-socket=8	## 

## Do some work:
ulimit -s unlimited
for i in 0.4 0.3 0.2 0.15 0.1 0.05 0.02 0.01 0.005
do
	sed -i '/AMIX/d' INCAR
    sed -i '$aAMIX = '$i'' INCAR
    AMIX_MAG=`echo "scale=4; $i*4" | bc -l`
	sed -i '$aAMIX_MAG = '$AMIX_MAG'' INCAR
    echo AMIX = $i
	echo AMIX_MAG = $AMIX_MAG
    echo --------------------------------------------------------------
    srun /opt/soft/vasp/5.3.2/vasp
	grep 'Elapsed' OUTCAR 
	echo --------------------------------------------------------------
done
